[[pages]]
path = "/"
screenshotTimestamp = "2026-05-22T13:00:52Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/efd0b7e7-831d-4aae-b8b0-72a7861a9115/2315124c-fc84-433e-a71e-aaf6a5a9ce65/z580qSq"

[[pages]]
path = "/admin"
screenshotTimestamp = "2026-05-22T10:17:46Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/efd0b7e7-831d-4aae-b8b0-72a7861a9115/2315124c-fc84-433e-a71e-aaf6a5a9ce65/cDVSy13"

[[pages]]
path = "/admin/dashboard"
screenshotTimestamp = "2026-05-22T02:26:13Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/efd0b7e7-831d-4aae-b8b0-72a7861a9115/2315124c-fc84-433e-a71e-aaf6a5a9ce65/fKgEssV"
